image:
  name: 192.168.1.101:5000/scaphandre
  tag: latest

port: 8080

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 75m
    memory: 100Mi

scaphandre:
  command: prometheus
  args: {"vm": ""}
  extraArgs:
#    containers:
#  rustBacktrace: '1'

# Run as root user to get proper permissions
userID: 0
groupID: 0

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  enabled: true
  interval: 1m
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: monitoring
