apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-cpu
spec:
  selector:
    matchLabels:
      app: block-cpu
  replicas: 1
  template:
    metadata:
      labels:
        app: block-cpu
    spec:
      containers:
      - name: block-cpu
        image: 192.168.1.101:5000/block_cpu:latest
        imagePullPolicy: IfNotPresent