apiVersion: apps/v1
kind: Deployment
# apiVersion: v1
# kind: Pod
metadata:
  name: block-cpu
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: block-cpu
  template:
    metadata:
      labels:
        app: block-cpu
    spec:
      # schedulerName: escheduler
      containers:
      - name: block-cpu
        image: 192.168.1.101:5000/block_cpu:latest
        imagePullPolicy: IfNotPresent
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       labelSelector:
      #         - matchExpressions:
      #           - key: kubernetes.io/hostname
      #             operator: In
      #             values:
      #             - block-cpu
  # containers:
  # - name: block-cpu
  #   image: 192.168.1.101:5000/block_cpu:latest
  #   imagePullPolicy: IfNotPresent